### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by alfredolp30** [arnekaiser/fastlane-plugin-huawei_appgallery#2]
https://github.com/arnekaiser/fastlane-plugin-huawei_appgallery/blob/2e86ded563006e9b43b34b7c19760f2547fd7a9a/lib/fastlane/plugin/huawei_appgallery/helper/huawei_appgallery_helper.rb#L117

**Comment by arnekaiser** [comment]
Sorry, but I cannot reproduce that. Please provide more information.
