### ISSUE TITLE
Connect time is exceed the limit time!

### ISSUE THREAD

**Issue by kokhong20** [arnekaiser/fastlane-plugin-huawei_appgallery#3]
Hi, I am getting this error `Authentication failed: {"errorCode":400100007,"errorMsg":"Connect time is exceed the limit time!","secretinfoList":null}` as I tried to run the lane again with same `signature` and `time`. Do we need to generate the new `signature` and `time` for every run?

**Comment by arnekaiser** [comment]
Yes, I think so. I don't know what the limit is, but in our setup we generate it every run.

**Comment by zkrige** [comment]
can you provide sample on how to generate this every time?

**Comment by arnekaiser** [comment]
See https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/obtain_token

But beware, this plugin uses the deprecated v1 api.
