### ISSUE TITLE
Migrate to Publishing API v2

### ISSUE THREAD

**Issue by MattSkala** [arnekaiser/fastlane-plugin-huawei_appgallery#4]
Publishing API v1 currently used by the plugin will be turned off soon. Are there any plans to migrate to API v2?

"To improve security of AppGallery Connect APIs, AppGallery Connect API V2 has added permission control and upgraded the key mechanism. AppGallery Connect API V1 will be brought offline in December, 2019. Please switch to AppGallery Connect API V2 as soon as possible."

https://developer.huawei.com/consumer/en/service/hms/catalog/publishingAPI.html

**Comment by arnekaiser** [comment]
Damn, I'm not sure if I find some time to change the API shortly. Pull requests are welcome. :)

**Comment by shr3jn** [comment]
> Publishing API v1 currently used by the plugin will be turned off soon. Are there any plans to migrate to API v2?
> 
> "To improve security of AppGallery Connect APIs, AppGallery Connect API V2 has added permission control and upgraded the key mechanism. AppGallery Connect API V1 will be brought offline in December, 2019. Please switch to AppGallery Connect API V2 as soon as possible."
> 
> https://developer.huawei.com/consumer/en/service/hms/catalog/publishingAPI.html

I've created another plugin to support API v2 for AppGallery, you can find it here: https://github.com/shr3jn/fastlane-plugin-huawei_appgallery_connect

**Comment by silviokuehn** [comment]
With 13628ff4d2b5fda496eaefbd9166b8f97b002bb5 (Version/Tag v0.2.0) publishing to API v2 should work now.
